import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import MapHolder from '../components/MapHolder'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AANI App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Poppins&display=optional" rel="stylesheet" />
        
      </Head>

      <main className={styles.main}>
        <Navbar/>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
        <HeroSection/>
        <MapHolder />
        <div id="map"></div>
      </main>

      <Footer/>
    </div>
  )
}
