import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import MapHolder from '../components/MapHolder'
import WelcomeAddress from '../components/WelcomeAddress'

export default function Home() {
  const e = React.createElement;

  return (
    <div className={styles.container}>
      <Head>

        <title>AANI App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Poppins&display=optional" rel="stylesheet" />
        <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
        <script src="mapdata.js"></script>
        <script src="countrymap.js"></script>
        <script>simplemaps_countrymap_mapdata.main_settings.auto_load = 'no';</script>
      </Head>

      <main className={styles.main}>
        <Navbar/>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
        <HeroSection/>
        <WelcomeAddress/>
        <MapHolder />
        <div id="react_container"></div>
        {e('div', {id:'map'})}
      </main>

      <Footer/>
    </div>
  )
}
